added reuasable workflow for PRs with a code basis of golang
hkraftno/.github pull request #2
Opened 2024-02-06 09:49 UTC by jvhenriksen

the reuable workflow consists of
- building the docker image based on the docker-compose.production.yml
- check the linting of the golang code
- running the go tests

One example usage of this reusable workflow would be:

```
name: Check PR - Golang
on:
  pull_request:
    branches:
      - main

env:
  GOPRIVATE: github.com/hkraftno/byge-common

jobs:
  CI:
    name: Testing Go
    uses: hkraftno/.github/.github/workflows/byge-create-PR-go.yml@main
    with:
      go_module_path: ./service/.
      docker_path: ./service/.docker
    secrets: inherit

```

2024-02-06 15:18 UTC, FredrikMorstad requested changes
Left some comments that could be looked at

2024-02-06 15:18 UTC, FredrikMorstad commented on .github/workflows/byge-create-PR-go.yml
> +          # install-mode: "goinstall"
Are these necessary?

2024-02-06 15:18 UTC, FredrikMorstad commented on .github/workflows/byge-create-PR-go.yml
> +          fi
Wouldn't the previous failed if the command exited with an error?

2024-02-06 15:32 UTC, jvhenriksen commented on .github/workflows/byge-create-PR-go.yml
> +          fi
seems like it is true what you said 👍

2024-02-06 15:32 UTC, jvhenriksen commented on .github/workflows/byge-create-PR-go.yml
> +          # install-mode: "goinstall"
🔥

2024-02-07 07:33 UTC, FredrikMorstad approved these changes
LGTM, very good to have a shared workflow for all services 👍

2024-02-07 09:04 UTC, merged